import json
from app.models.db_models import ScanRecordDB


def _decode_list(value: str) -> list:
    """Safely decode a JSON-encoded list string back to a Python list."""
    if not value:
        return []
    try:
        result = json.loads(value)
        return result if isinstance(result, list) else []
    except (json.JSONDecodeError, TypeError):
        return []


def build_report_text(record: ScanRecordDB) -> str:
    """
    Takes a ScanRecordDB instance and returns a formatted plain-text safety report.
    JSON-string list fields are decoded back to real lists before formatting.
    """
    red_flags        = _decode_list(record.redFlags)
    suspicious       = _decode_list(record.suspiciousPhrases)
    safe_actions     = _decode_list(record.safeActions)
    do_not_do        = _decode_list(record.doNotDo)

    def bulleted(items: list, prefix: str = "-") -> str:
        if not items:
            return f"  {prefix} N/A"
        return "\n".join(f"  {prefix} {item}" for item in items)

    report = f"""
========================================
   FraudLens PK — Safety Report
========================================

Scan ID    : {record.id}
Date       : {record.createdAt.strftime("%Y-%m-%d %H:%M:%S UTC") if record.createdAt else "N/A"}
Input Type : {record.inputType}

----------------------------------------
RISK ASSESSMENT
----------------------------------------
Risk Level  : {record.riskLevel}
Confidence  : {record.confidence}%
Scam Type   : {record.scamType}

----------------------------------------
SUMMARY
----------------------------------------
{record.summary}

----------------------------------------
RED FLAGS
----------------------------------------
{bulleted(red_flags, "[!]")}

----------------------------------------
SUSPICIOUS PHRASES DETECTED
----------------------------------------
{bulleted(suspicious, ">>")}

----------------------------------------
EXPLANATION (English)
----------------------------------------
{record.englishExplanation}

----------------------------------------
EXPLANATION (Roman Urdu)
----------------------------------------
{record.urduExplanation}

----------------------------------------
SAFE ACTIONS -- What you SHOULD do
----------------------------------------
{bulleted(safe_actions, "[+]")}

----------------------------------------
DO NOT DO -- What you must AVOID
----------------------------------------
{bulleted(do_not_do, "[X]")}

========================================
   Report generated by FraudLens PK
   Stay safe. Stay aware.
========================================
""".strip()

    return report
